services:
  - type: web
    name: habit-quest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "habit_quest:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: habit-quest-db
          property: connectionString
      - key: FLASK_APP
        value: habit_quest
      - key: FLASK_ENV
        value: production

databases:
  - name: habit-quest-db
    databaseName: habitquest
    user: habitquest 