services:
  - type: web
    name: habit-quest
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: habit_quest
      - key: FLASK_ENV
        value: production
    dependencies:
      - name: habit-quest-db
    envVarsFromDatabase:
      - key: DATABASE_URL
        fromDatabase: habit-quest-db

databases:
  - name: habit-quest-db
    databaseName: habitquest
    user: habitquest
    plan: free 